### ISSUE TITLE
Where can i place Callback function with Glue.compose.bind 

### ISSUE THREAD

**Issue by sibinx7** [hapijs/glue#100]
```
const Glue = require('glue')
const Manifest = require('./manifest')

const composeOptions = {
  relativeTo: __dirname
}
Glue.compose.bind(Glue, Manifest.get('/'), composeOptions)

```
```
#manifest file 
    {
      plugin:{
        register: 'bell'
      }
    },
```
Where i can pass callback to register **[bell](https://github.com/hapijs/bell/blob/master/API.md)** auth stractegy

**Comment by csrl** [comment]
The glue configuration schema for a plugin registration is:
```
{
  plugin: {
    register: <plugin_to_register>,
    options: <plugin_options>
  },
  options: <registration_options>
}
```

Which translates into a hapi server call of:

```
server.register({register: <plugin_to_register>, options: <plugin_options>}, <registration_options>)
```
So if you follow bell's documentation, the mapping should become apparent.

**Comment by sibinx7** [comment]
Thanks @csrl 

Can you give me an example with this 

```
server.register(require('bell'), function (err) {
    server.auth.strategy('twitter', 'bell', {
        provider: 'twitter',
        password: 'cookie_encryption_password_secure',
        clientId: 'my_twitter_client_id',
        clientSecret: 'my_twitter_client_secret',
        isSecure: false     // Terrible idea but required if not using HTTPS especially if developing locally
    });
})
```
Can u give me one example with this.

Project use Glue.compose.bind() method than Glue.compose, second one, we can use callback
```
Glue.compose(manifest, options, (err,server) => {})
```

1. How can i do with `Glue.compose.bind`
2. How can i add this on 
```
{
  plugin: {
    register: <plugin_to_register>,
    options: <plugin_options>
  },
  options: <registration_options>
}
```

Thanks in advance ...

**Comment by csrl** [comment]
call server.auth.strategy in the compose callback that provides the 'server' object.

**Comment by sibinx7** [comment]
```
Glue.compose.bind(Glue, Manifest.get('/'), composeOptions, composeCallback)
```
when i add callback ,i got argument error

 throw new Error(msgs.join(' ') || 'Unknown error');
    ^
Error: Invalid number of arguments

**Comment by csrl** [comment]
What is the purpose of using bind? You'll get "Invalid number of arguments" error if you pass more than 3 arguments to compose, but from what you pasted you are not doing that.  The only thing I can think is you are doing something else weird since you are using bind in the first place.

In any case, I can't reproduce the error:
```
$ node
> var Glue = require("./")
undefined
> Glue.compose.bind(Glue,{},{},function (err,server){})
[Function: bound ]
> 
```
You'll have to provide a minimal example that produces the error that I can test.

**Comment by csrl** [comment]
Feel free to reopen if you still have any question.
