### ISSUE TITLE
setting cache option throws error "cannot read property of _hoekOnce of undefined"

### ISSUE THREAD

**Issue by saurabhghewari** [hapijs/glue#106]
const manifest = {
          server : {
               cache : 'catbox-redis',
		port : 8000,
		compression : { minBytes : 1024 },
		debug: { request : ['*'] },
		host : '0.0.0.0',
		load : {
			sampleInterval : 1000
		},
          }
    }

The "cache" key is throwing error while starting the server

Error is "TypeError: Cannot read property '_hoekOnce' of undefined".

Removing cache from the manifest everything works fine.

Hapi- 17.0.1
Glue:- 5.0.0
Catbox:- 3.1.1 (catbox-redis).

Is there something am I missing in Manifest.

**Comment by WesTyler** [comment]
Looks like `catbox-redis` has not been updated to support hapi 17 yet. You can track that issue [here](https://github.com/hapijs/catbox-redis/issues/76).

**Comment by saurabhghewari** [comment]
Ohh. Thank you for the info.

**Comment by LoicMahieu** [comment]
`catbox-redis@4.0.0` released with hapi 17 support! Thanks to @EgoAleSum @Marsup
