### ISSUE TITLE
Invalid server options

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [hapijs/glue#107]
This is my manifest object. If I ramove the connections from server Glue returns a Promise and If I add this I get error 

```
const catboxMemory = require('catbox-memory');

const manifest = {
  server: {
    cache: {
      engine: catboxMemory,
    },
    connections: {
      routes: {
        cors: {
          origin: ['*'],
          additionalHeaders: ['x-logintoken'],
          additionalExposedHeaders: ['x-logintoken'],
          credentials: true,
        }
      }
    }
  }
};
```

**<rejected> { AssertionError [ERR_ASSERTION]: Invalid server options** 
&
**[1] "connections" is not allowed**

I am trying out Glue first time can you please guide me if I am doing something wrong.

**"glue": "5.0.0",**
**"hapi": "16.6.2",**

Thank you.

**Comment by Marsup** [comment]
Glue 5 is made for hapi 17, not 16, you should revert to 4.
