### ISSUE TITLE
How can I use standard modules as plugins?

### ISSUE THREAD

**Issue by avbalen** [hapijs/glue#109]
In Glue 4.2.0, I used a number of standard modules (hapi-auth-jwt2, lout,...) as plugin in the manifest.
However, if I do the same in Glue 5.0.0 with this manifest

   register: { 
        plugins: [
            'hapi-auth-jwt2',
            'lout', 
            'inert', 
            'vision',
            { plugin: 'visionary',
                options: {
                    engines: { pug: 'pug' },
                    relativeTo: __dirname,
                    path: './server/web'
                }
            },.....
I get the message "name" is required (invalid plugin options).
What is the correct manifest for Hapi 17 and Glue 5, using Confidence as store?

**Comment by WesTyler** [comment]
That is the error message you get from hapi v17 when you register a plugin
that hasn’t been updated from hapi v16 yet.


I think it may be hapi-auth-jwt2 in that list, but I’m not sure.
Check that the plugins you’re using have all been updated to hapi 17 and
that you are using the proper version

**Comment by avbalen** [comment]
Thanks for the quick answer.
Unfortunately many plugins like hapi-auth-jwt2, lout, vision have not yet been updated to hapi v17.
I think I might better postpone the move to hapi v17 for my application until the "dust has settled", i.e. most plugin maintainers had the chance to do the update. Moving to the new version is quite some effort, I am afraid.

**Comment by WesTyler** [comment]
Vision is actually updated in v5, but yeah lout and hapi-auth-jwt2 aren't yet. :\
