### ISSUE TITLE
Relative paths are bugged

### ISSUE THREAD

**Issue by gagle** [hapijs/glue#11]
You can't use a relative path to require a module from inside a module that will be stored in the node_modules folder. If you have a manifest with a path `./my-plugin`, this will be resolved to `require('<...>/node_modules/glue/my-plugin')` because relative path used with require() are relative to the __dirname.

The solution is to use join the process.cwd to the relative paths:

```javascript
path = Path.join(process.cwd(), path);
```

**Comment by csrl** [comment]
You can set the 'relativeTo' option to the path that you want to load the plugins relative to using the output of the code you provided.
