### ISSUE TITLE
Using glue with hapi-mongoose

### ISSUE THREAD

**Issue by Calinou** [hapijs/glue#118]
#### Context

* *node version*: 8.11.3
* *glue version*: 5.0.0
* *hapi version*: 17.5.2

#### What are you trying to achieve or the steps to reproduce?

I'm wondering how to make [hapi-mongoose](https://github.com/asilluron/hapi-mongoose)'s database connection object available in plugins without copy-pasting too much code around. From what I've seen, it should also be available in `require()`'d route handlers (which I've had trouble doing).

I tried appending them to `server.app` in my main `index.js` file, but `server.app` was still empty in any plugins. I also tried defining methods that retrieved the hapi-mongoose objects and using `server.bind()`. I even tried creating a dedicated `models` plugin, adding it as a dependency and loading routes in the `after` callback, without success.

Here's the manifest I'm using:

```js
const manifest = {
  server: {
    host: "localhost",
    port: 3000,
  },
  register: {
    plugins: [
      {
        plugin: "blipp",
        options: {
          showAuth: true,
        },
      },
      {
        plugin: "hapi-mongoose",
        options: {
          url: "mongodb://localhost:27017",
          promises: "native",
          mongooseOptions: {
            dbName: "myDatabase",
          },
        },
      },
      {
        plugin: "./notifications",
        routes: {
          prefix: "/api/notifications",
        },
      },
    ],
  },
};
```

For the record, the hapi-mongoose utility objects can be accessed like this:

```js
// Database connection object
server.plugins["hapi-mongoose"].connection
// Used to define schemas and models
server.plugins["hapi-mongoose"].lib
```

**Comment by WesTyler** [comment]
I'm not sure what the question is here. You've already found where the connection object is available, at `server.plugins["hapi-mongoose"].connection`.

The `register` function of all of you plugins get passed the `server` parameter, and you can access the server object on request handlers in your plugins via `request.server` as well.

**Comment by Calinou** [comment]
@WesTyler Thanks for the reply :smiley:

I ended up placing models into separate files, therefore I had to find out a way to make the hapi-mongoose objects available in schema files; I passed the `server` object to the `require()` function which returns the schema. It's not ideal as it still requires copy-pasting two lines in each schema, but I can deal with that.

#### `index.js`

```javascript
exports.register = server => {
  // Load models
  server.app.Notification = require("./models/notification")(server);

  // ...
```

____

#### `models/notification.js`

```javascript
module.exports = server => {
  const db = server.plugins["hapi-mongoose"].connection;
  const Schema = server.plugins["hapi-mongoose"].lib.Schema;

  return db.model(
    "Notification",
    new Schema({
      // ...
    }),
  );
};
```

I think this is resolved for now, so I'll close this issue.

**Comment by WesTyler** [comment]
Ah, ok, I see now. Thanks for clarifying.

FWIW, that's a similar pattern we use when we need props or methods on the server object inside of plugin application logic.

Glad you found a working solution 👍

**Comment by dellamina** [comment]
@WesTyler Nice solution, I took it one step further:

```js
// index.js
exports.register = server => {
  const hapiMongoose = server.plugins["hapi-mongoose"];
  const mongo = {
    db: hapiMongoose.connection,
    mongoose: hapiMongoose.lib,
    Schema: hapiMongoose.lib.Schema
  }
  server.app.Notification = require("./models/notification")(mongo);
```

and then in your model you can take advantage of object destructuring like so:

```js
// models/notification.js
module.exports = mongo => {
  const { db, mongoose, Schema } = mongo;
```
