### ISSUE TITLE
server.events is undefined after glue compose

### ISSUE THREAD

**Issue by liiijz** [hapijs/glue#119]
#### Context

* *node version*: v10.7.0
* *glue version*: v4.2.1
* *hapi version*: v17.1.1
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce ?

below codes
Why is **server.events** undefined?
I want to use server.events.on... as doc mentioned

```js
const composer = async () => {
  const server = await Glue.compose(Manifest, composeOptions);
  await server.start();
  console.log(server.events);
  server.log('error', `Server started @ ${server.info.uri}`);
  return server;
}
```

**Comment by WesTyler** [comment]
I haven't taken a look at this specifically, but try using Glue version 5. There was a fairly significant refactor of the internals to support hapi 17. I would expect lots of weird behavior and breakages using Glue@4 with hapi@17

**Comment by WesTyler** [comment]
If you do want to update to Glue 5 from Glue 4, I wrote a short post on the differences [here](https://tech.xogrp.com/migrating-to-hapi-v17-plugin-structure-and-glue-manifests-a7b3c3d551f2)

**Comment by liiijz** [comment]
thanks! after update to glue 5, it's OK!

**Comment by WesTyler** [comment]
Excellent! Glad to hear it!
