### ISSUE TITLE
Server options load support? Migrating from hapi 16 -> 17

### ISSUE THREAD

**Issue by eitah** [hapijs/glue#123]
I'm migrating from hapi 16 -> 17.

I see the new syntax for passing load options in hapi is to pass `server.options.load` (example max event loop delay as documented here `https://github.com/hapijs/hapi/blob/master/API.md#-serveroptionsload`). The docs above label it as the Hapi api for v18.x but since that’s the development version I think the settings are identical for v17 as per the release notes here hapijs/hapi#3658

But when i try to pass those in my manifest options the Joi schema dings me for not being one of the options below. would there be plans to include additional happy config options in glue eventually? Or how would you recommend I pass options to the hapi Server outside of those supported by glue?

We're on node 8 and Express if that matters.
Thanks,
Eli

```
relativeTo: Joi.string(),
preRegister: Joi.func().allow(false)
```

**Comment by eitah** [comment]
PS- the docs above label it as the Hapi api for v18.x but since that’s the development version I think the settings are identical for v17 as per the release notes here https://github.com/hapijs/hapi/issues/3658

**Comment by csrl** [comment]
Server options go into  `manifest.server`, not glue compose options.  If that is what you are doing, then please provide example code that fails.

**Comment by eitah** [comment]
I am following along with the example usage here https://github.com/hapijs/glue/blob/master/API.md#usage

that code abstracts away access to the call to this code so that I never write the line
 `const server = Hapi.server({ cache: [{ engine: require('redis') }], port: 8000 });`

I dont understand how to access the Hapi.server options object to pass additional options if glue compose returns an instance of a server already prepared.

**Comment by eitah** [comment]
To be specific about my code, i am passing manifest with the below options, and the Joi validation only allows the load object to be passed.

`    const manifest = {
        server: {
            maxHeapUsedBytes,
            maxRssBytes,
            maxEventLoopDelay,
            load: {
                sampleInterval: 1000, // send 503 when server starts maxing out on resources
            },
        },
        // handlebars,
        // components,
        // routes
    };`
`
[1] "maxHeapUsedBytes" is not allowed
[2] "maxRssBytes" is not allowed
[3] "maxEventLoopDelay" is not allowed
`

**Comment by csrl** [comment]
Does it work with calling `Hapi.server({ load: { sampleInterval: 1000, maxHeapUsedBytes: 1073741824, }, })` directly?  As you show, the error comes from hapi, not glue.

**Comment by eitah** [comment]
that did it! thank you for the correction. I merely had the options object configured incorrectly.
Thanks again.
