### ISSUE TITLE
Add typescript type definitions

### ISSUE THREAD

**Issue by svallory** [hapijs/glue#136]
For people using Typescript it would be awesome to get IDE help and type checks when writing manifests. I know there's a `@types/hapi__glue` package, but officially supporting it would mean it's always up-to-date with the latest version of glue

**Comment by Nargonath** [comment]
There is an ongoing project in the organization to bring TypeScript definition to every project. Right now Eran is trying to finance such effort through a crowdfunding campaign: https://www.gofundme.com/f/hapi-ts. As you seem to care about it, perhaps consider asking your employer to participate. Individual participations are also welcomed of course.

Merry Christmas. :christmas_tree:

**Comment by hueniverse** [comment]
This will happen over time based on available resources. Closing as it is tracked as part of a larger effort.
