### ISSUE TITLE
Loading manifest into an existing server

### ISSUE THREAD

**Issue by jeffm13** [hapijs/glue#16]
Any chance of an alternate mechanism for glue to load a manifest into an existing server object?  My use case is for a 'reusable' server that forces consistent log, ops, security, and documentation plugins.  One way to do that might be to 'preload' a number of plugins into a server, and then load a manifest on top of the existing server.  Composition of this 'standard' server would then consist of specific API plugins and their requirements. There are other ways to do this, but I thought I'd ask...

**Comment by csrl** [comment]
I'd be open to a pull request for this.  Something as simple as providing the server to use in the compose options parameter might work.  I'd be interested in seeing alternative approaches as well.

**Comment by jeffm13** [comment]
I handled my initial use case with a preplugin function.  But it was still too brittle.  So I think I'm leaning toward an alternate loader--similar to rejoice, but it will enforce a default security scheme and merge the provided manifest with a manifest containing 'standard' plug-ins prior to loading with glue.
