### ISSUE TITLE
Conflicting routes when using prefix

### ISSUE THREAD

**Issue by johanalkstal** [hapijs/glue#30]
I have a manifest that looks like the following,

```
module.exports = {
  connections: [{
    host: 'localhost',
    port: 1337
  }],
  plugins: [
    {
      blipp: null
    },
    {
      vision: null
    },
    {
      './lib/plugins/user': null
    },
    {
      './lib/plugins/admin': {
        routes: {
          prefix: '/admin'
        }
      }
    }]
};
```

Both plugins adds a route that looks like this,

```
 server.route([
  { method: 'GET', path: '/', config: indexConfig }
]);
```

I get `Error: New route / conflicts with existing /` error. 

Am I setting up the manifest wrong or are my expectations of how it should work wrong?

**Comment by marinintim** [comment]
@johanalkstal: right now you should wrap your options you pass to plugin with `[]`, it is discussed in #31.

**Comment by johanalkstal** [comment]
Thanks!
