### ISSUE TITLE
Hapi-lts support

### ISSUE THREAD

**Issue by joseph-norman** [hapijs/glue#43]
Hi guys,

I've noticed that in the `package.json` the [hapi-lts](https://www.npmjs.com/package/hapi-lts) isn't set as a dependency nor is it used in code. Would you accept a PR for this to be added in? Apologies if I've missed something here.

**Comment by AdriVanHoudt** [comment]
If I am correct Hapi-lts is just the 9.x.x branch which is in the package.json

**Comment by joseph-norman** [comment]
Oh is it? In that case I'll try that - thanks!

**Comment by AdriVanHoudt** [comment]
I think it is not 100% sure though ^^
