### ISSUE TITLE
how to pass routes: { prefix: '/prefix' } for object notation

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/glue#45]
Hi,

In the documentation it's stated, that we can pass options for ```server.register``` when passing the plugin options as array, like this:
```javascript
'./app/web/api/auth': [
                {routes: {prefix: '/auth'}, options: {}}
            ],
```

However, I assume it should be somehow possible to do the same, when registering the plugin with object as options, something like this:
```javascript
'./app/web/api/users': {routes: {prefix: '/users'}},
```

However, it doesn't work. Any thoughts if it's possible?

Regards,

**Comment by csrl** [comment]
@PavelPolyakov  see issue #31.  This will be addressed in v3.0
