### ISSUE TITLE
register all js files inside a folder, instead of registering one by one

### ISSUE THREAD

**Issue by amgohan** [hapijs/glue#55]
did Glue support scanning and register all js inside a folder, especially when there are no options to pass to this plugins. Something like : 

    registrations: [
        {
             plugins : './server/api/controllers/*.js'
        },
        ....
    ]

Or is there another elegant solution to do that.

**Comment by csrl** [comment]
It does not.  You'd need to wrap with a your own helper code to populate the registrations array.

**Comment by amgohan** [comment]
I created a hapi plugin to scan and register hapi methods, take a look : https://github.com/amgohan/hapi-methods-injection
