### ISSUE TITLE
No error when registering a plugin, server silently ends

### ISSUE THREAD

**Issue by garfbargle** [hapijs/glue#59]
## Explanation
Registering some plugins is causing my composer to kill the server process but there is no explanation or errors. If I remove this plugin registration my server stays running as expected.

## Setup
Given this registrations configuration:
``` 
registrations: [
     {
        plugin: {
          register: 'lout'
        }
      }
    ] 
```

```
Composer(function (err, server) {

  if (err) {
    throw err;
  }

  server.start(() => {
    console.log('Server running at: ' + server.info.uri);
  });

});
```

### Expected
error returned 

### Actual
server starts with no error then silently quits.

**Comment by garfbargle** [comment]
Ignore. Something else is going on that I'm not seeing and silently shutting the server off.

**Comment by csrl** [comment]
You can open an issue with the hapi server project.  Glue doesn't control what hapi does with plugins that do not exist.  In any case, you can catch the error hapi is throwing.
