### ISSUE TITLE
No documentation on new schema

### ISSUE THREAD

**Issue by tanepiper** [hapijs/glue#60]
Joi of Jois, today when I deployed our API server it broke.

After digging around and some time debugging I found that `plugins` is no longer a property we can use in a config file, but some kind of new `registrations` array where you have to pass in each plugin as as an object, and a new options layout too.

Can you PLEASE document the Glue schema, and going forward advise of any changes as major is this.

**Comment by tanepiper** [comment]
Apologies, saw the new API docs - just had a rather frustrating morning with the new version of Glue.....

**Comment by devinivy** [comment]
> Joi of Jois
:P 

Yes, glue came out with a new major version, which indicates that there are breaking changes.  The new glue manifest format makes the order of plugin registration to be well-defined and more transparent to the developer :)

**Comment by Marsup** [comment]
Just wondering, how can you see that only when deploying ? Don't you test locally before ?

**Comment by tanepiper** [comment]
@Marsup @devinivy In the package.json `"glue": "^2.4.0",` was set, so I have no idea why it broken when I deployed. But when starting up the server was getting Joi errors.  Took a while to dig around and find that it was the internal manifest, and from that the new API.

I'll most likely set the package.json to a tilde for try enforce only minor updates.

@devinivy I would say that while the API docs are there, there is no clear upgrade path specified in the release notes or readme (something like https://github.com/rackt/redux/releases/tag/v3.1.0).  It was quite a fundamental schema change, and even reading the docs it still isn't clear if you need to pass in plugin options (no route/label options) that you have to use the `plugin.register` format.
