### ISSUE TITLE
Using Glue with Lab

### ISSUE THREAD

**Issue by sean-hill** [hapijs/glue#69]
Hey, in all the examples for unit testing an API using the Lab library, they require their index.js file and use module.exports = server to get access to the server in their tests. However, with Glue we are handed back the server in the callback. How would it be possible to use these two libraries together?

**Comment by vdeturckheim** [comment]
Yes, you can see my example (old glue syntax) [here](https://github.com/vdeturckheim/sticky_public/blob/master/test/api/routes.test.js).

**Comment by devinivy** [comment]
This becomes more complicated when you want to use the same server throughout many tests.  I created a utility named labbable with this exact use-case in mind, https://github.com/devinivy/labbable#with-glue.
