### ISSUE TITLE
Make compose callback always execute async

### ISSUE THREAD

**Issue by davidjamesstone** [hapijs/glue#72]
Let me start by saying thanks for Glue - it's a great, really useful module.

One issue I have is with the `compose` method. It has an optional callback which can be invoked sync or async depending if any plugins being registered are themselves async (they call their `next` function asynchronously.)

This behaviour can cause [astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and [releases](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony) [Zalgo](http://t.umblr.com/redirect?z=http%3A%2F%2Fblog.ometer.com%2F2011%2F07%2F24%2Fcallbacks-synchronous-and-asynchronous%2F&t=NjY0NjAwMWQ2ZGNlOWFlMDBjZTVjM2NhNjlhNmRkMzM4ODE3MTIxYiw3NDduUUZ0VQ%3D%3D)

Would you consider forcing async behaviour with a little `process.nextTick`? Apologies if this has already been discussed.

Related to https://github.com/hapijs/glue/issues/14

**Comment by csrl** [comment]
I'm thinking this would be considered a breaking change and require a major version bump.  Opinions?

**Comment by devinivy** [comment]
I agree that it would be a breaking change.  Given that it's accepted for hapi plugins to behave sync or async, it's pretty hard for me to say whether I agree with this change or not.  I definitely agree that it's preferable for async-looking things to behave asynchronously.  A change here almost implies that `server.register()` itself should be changed, which is hard for me to agree with outright.

**Comment by davidjamesstone** [comment]
I'd like to see `server.register` change. This issue then goes away but that's probably much harder to change I guess, and has more implications.

FWIW, I think it's still a worthwhile (breaking) change for `glue`.
Writing plugins has always feel async-ish to me, given you need to call `next` ala expressjs.

...just my 2 cents

**Comment by devinivy** [comment]
Worth adding, the hapi style guide is at least clear on the point that callbacks named `next` are the only ones that may occur before the next tick: http://hapijs.com/styleguide#callback

**Comment by davidjamesstone** [comment]
Thanks for that link, I hadn't seen it before and didn't know about the next/callback naming convention.

I guess you do get used to it though I'm not sure it's entirely clear to newcomers to hapi-land.

My concern for `glue` is It means that code could break/behaviour change if an async plugin is introduced at a later date.

E.g. This test code is good until an async plugin is registered in the manifest, after which module.exports would not be initialized:

```js
Glue.compose(manifest, options, (err, server) => {
  if (!module.parent) {
    server.start(() => {
      console.log('Server started on port:', server.info.uri);
    });
  } else {
    module.exports = server;
  }
});
```

I see your `labbable` addresses this 👍

**Comment by csrl** [comment]
I think the short term "fix" is to change 'callback' to 'next' in glue.compose.

Regardless of server.register behavior, if glue.compose is called with a manifest that has an empty registrations, it still needs to maintain async behavior if the compose parameter is to be called 'callback', if we are to abide by the style guide.
