### ISSUE TITLE
Allow options in plugins...

### ISSUE THREAD

**Issue by simlevesque** [hapijs/glue#75]
The plugin allows me to add options to server.register() but I can't set plugin specific options. You don't really support Hapi 15 if you don't allow that.

I'll make a PR.

**Comment by simlevesque** [comment]
Here is the doc : 

http://hapijs.com/api#serverregisterplugins-options-callback

Example : 
```
server.register({
    register: require('plugin_name'),
    options: {
        message: 'hello'
    }
 }, (err) => {

     if (err) {
         console.log('Failed loading plugin');
     }
 });
```

**Comment by csrl** [comment]
I don't understand the problem.  Nothing has changed in regards to plugins and server.register in hapi v15.

Plugin specific options and register options are supported.  Can you provide an example manifest that is failing to behave as you expect?
