### ISSUE TITLE
Getting deprecation warning

### ISSUE THREAD

**Issue by RezaOwliaei** [hapijs/glue#80]
I just following deprication warning with node v7.1.0:
`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

**Comment by csrl** [comment]
Glue does not use os.tmpDir().  It looks like hapi does.  Please file a ticket against hapi.

**Comment by Marsup** [comment]
This will be fixed with hapi 15.2.1. See https://github.com/hapijs/hapi/pull/3368.
