### ISSUE TITLE
Joi.array() does not accept arguments

### ISSUE THREAD

**Issue by WesTyler** [hapijs/glue#83]
This does not result in thrown errors for Joi v10.0.2 or below, but it also does not do anything.

To pave the way for an assumed-to-be-eventual upgrade to Joi v10 (allowing for support for Hapi v16), usage of `Joi.array(Joi.object())` should be removed/refactored to `Joi.array().items(Joi.object())`.
Looking at https://github.com/hapijs/glue/blob/master/lib/index.js#L24.

**Comment by WesTyler** [comment]
PR to address incoming

**Comment by ferrao** [comment]
+1
