### ISSUE TITLE
options: {showAuth: true} throws error

### ISSUE THREAD

**Issue by jack0088** [hapijs/glue#86]
Is this me or is it a bug? As soon as I add showAuth to the options I get an error: _"showAuth" is not allowed_

Here's my manifest:

`const manifest = {
    server: {},
    connections: [
        {host: "localhost", port: 8000}
    ],
    registrations: [
        {plugin: "hapi-auth-basic"},
        {plugin: "blipp", options: {showAuth: true}}
    ]
}`

Now the interesting part. If I remove showAuth from options and then go to the module _/node_modules/blipp/lib/index.js_ and edit _line 11_ to be `showAuth: Joi.boolean().default(true) // instead of false`
then it works!

How can this be?

**Comment by WesTyler** [comment]
That sounds like an issue with blipp, not glue. That error message is in fact a Joi error message, and you were able to fix the issue by modifying the blipp src.

**Comment by jack0088** [comment]
oh, sorry! I didn't noticed that I posted this not in the blipp repo. (had both opened side by side)
