### ISSUE TITLE
nes option: onMessage

### ISSUE THREAD

**Issue by sandangel** [hapijs/glue#87]
According to https://github.com/hapijs/nes/blob/master/API.md#registration nes has a config option when register called onMessage. How can I declare a function with the signature function(socket, message, next)
in config.json file, or I have to split nes register part to another js file?

**Comment by csrl** [comment]
glue doesn't take a "config.json" file.  Are you using you using the rejoice plugin perhaps?  The manifest you pass to Glue.compose() can have a function assigned to the relevant plugin config field.

**Comment by sandangel** [comment]
I read Hapi.js in action book and it show that we can use a config.json file to pass to manifest

index.js

'use strict';

const Glue = require('glue');

const manifest = require('./config.json');

const options = {
    relativeTo: __dirname
};

Glue.compose(manifest, options, (err, server) => {

    if (err) {
        throw err;
    }
    server.start((err) => {

        if (err) {
            throw err;
        }

        console.log('Server started at: ' + server.info.uri);
    });
});

And my config.json file here (Sorry github not allow to upload .json file)

[config.txt](https://github.com/hapijs/glue/files/670965/config.txt)

**Comment by csrl** [comment]
ok.  You can manipulate your config.json after loading it to be in the form that you want before passing it as a manifest to glue.  There is nothing in glue to help with this.
