### ISSUE TITLE
Callback is not called when options or manifest Assertion fails

### ISSUE THREAD

**Issue by valdemon** [hapijs/glue#90]
The assertion of options and manifests should be wrapped in `try...catch` clause due to call the `callback(err)` in case of an error.

Following code:
```javascript
Joi.assert(options, internals.schema.options, 'Invalid options');
Joi.assert(manifest, internals.schema.manifest, 'Invalid manifest');
```

should be wrapped by `try...catch` and relocated after the optional Promise wrapping.

**Comment by Marsup** [comment]
Unless he wants it to crash the process, which seems like it, just like the assert 2 lines above.

**Comment by devinivy** [comment]
The idea is that if these assertions don't hold it is an unrecoverable programmer error, not dissimilar in character to what would happen if you tried to call `undefined` as a function, or read a property of `null`.

**Comment by valdemon** [comment]
Ok, got it :) I just thought when one provides a contract with the error, either provided by a callback or promise then I can rely on it - means, that I'm able to handle the error in the right place (callback function, or promise `catch` clause. You could be right in case of some dummy programming, when one would ignore error objects given according to mentioned contract. So i understand you were worried about such situations, right?

**Comment by devinivy** [comment]
Ultimately I defer to @csrl, but that's my interpretation of it :)

**Comment by valdemon** [comment]
Ok, thanks for the explanation :) Anyway, also thanks for this cool & helping library! Closing the issue.

**Comment by csrl** [comment]
It is how hapi code is written - wrong types / schema validation failures generally throw exceptions.  Its considered a non recoverable programming error.  I've no strong opinion on it, but grep the hapi code for assert and you'll see its the common practice.
