### ISSUE TITLE
Promise Error doesn't make it to Catch

### ISSUE THREAD

**Issue by dhershman1** [hapijs/glue#96]
It doesn't seem like the promise returned by glue makes it to the catch you add onto compose, If an issue happens within the config (say I were to change one of my plugin names to cheese) you get back an unhandled promise rejection.

**Please note**: This applies for any issue not just plugin registering.

Example setup:
```js
const manifest = require('./glue.config.js');
const glue = require('glue');

glue.compose(manifest).then(server => {
	server.start(error => {
		if (error) {
			throw error;
		}

		console.log(`Server running at: ${server.info.uri}`);
	});
})
.catch(err => {
	throw err;
});
```
The **working** glue config example: 
```js
module.exports = {
	connections: [{
		port: process.env.APP_PORT || 5000
	}],
	registrations: [{
		plugin: 'h2o2'
	}]
};
```
The **broken** glue config example
```js
module.exports = {
	connections: [{
		port: process.env.APP_PORT || 5000
	}],
	registrations: [{
		plugin: 'cheese'
	}]
};
```

**Comment by dhershman1** [comment]
The main reason this doesn't work is because glue was built on the callback basis, just inserting a logic check and returning a promise doesn't work. You either have to go promise or callback trying to do both is bad practice anyway. 

As well as the requires (which is why not found plugins break obviously) may need a try catch in order to send it up the totem pole to the promise. 

It's probably best to stick to using the callback functionality instead of promise functionality currently since it technically is broken.

**Comment by devinivy** [comment]
If you throw in a catch block, then you'll create another rejected promise.  My guess is that if you log the error rather than throw it, you will not have an unhandled rejection.

**Comment by dhershman1** [comment]
Not sure why I didn't think to swap out that throw. I've been looking at this project for too long. Oh well, thanks for the clear up to my oopsies. ¯\_(ツ)_/¯

**Comment by devinivy** [comment]
Sure thing! :D 🍻
